repos:
  - hooks:
      # Run the linter.
      - id: ruff
        # Exclude jupyter notebooks and pyi files.
        types_or: [ python ]
        args: [--fix, --exit-non-zero-on-fix]
      # Run the formatter.
      - id: ruff-format
    repo: https://github.com/astral-sh/ruff-pre-commit
    rev: "v0.6.3"
  - hooks:
      # Checks for giant files. We will set limit to 10MB
      - id: check-added-large-files
        args: [--maxkb=10240]
      # Trims trailing whitespaces
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
      # Attempts to load all yaml files to verify syntax.
      - id: check-yaml
      # Attempts to load all TOML files to verify syntax.
      - id: check-toml
      # Auto-formats JSON files and checks they are correctly formatted
      - id: check-json
        exclude: '^.vscode/.*\.json$|^data/.*\.json$'
      # Checks that all your JSON files are pretty
      - id: pretty-format-json
        exclude: '^.vscode/.*\.json$|^data/.*\.json$'
        args: ['--autofix']
      # Checks for a common error of placing code before the docstring.
      - id: check-docstring-first
    repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0

